### ISSUE TITLE
Change AirPlayRoutePickerView icon?

### ISSUE THREAD

**Issue by nimisis** [MrJai/flutter_to_airplay#10]
This is excellent! Would it be possible to have the ability to set the icon. At the moment the default seems to be the 'airplayaudio' icon. Thanks.

**Comment by MrJai** [comment]
@nimisis Thank you for using this package.

It's not a custom icon, but it is something that Apple provides with the AVRoutePickerView. I was looking into some native solution but looks like Apple doesn't let you customize this icon. As discussed in this thread,
[Setting AVRoutePickerView icon](https://developer.apple.com/forums/thread/115970)

I will keep looking for some possibility, otherwise I will implement some workaround over the weekend.

**Comment by MrJai** [comment]
I did check it out. As I confirmed Apple doesn't let you change the AVRoutePickerView Icon, but what you can do is, you can use the Stack widget to place any Icon on AVRoutePickerView and set AVRoutePickerView colors to transparent. Please see the example,

`Container(
              width: 44.0,
              height: 44.0,
              child: Stack(
                alignment: Alignment.center,
                children: [
                  Icon(
                    Icons.play_circle_filled,
                  ),
                  AirPlayRoutePickerView(
                    tintColor: Colors.transparent,
                    activeTintColor: Colors.transparent,
                    backgroundColor: Colors.transparent,
                  ),
                ],
              ),
            ),`

It will change Airplay Icon to Play Icon, but will still perform the required functionality.


![SR5](https://user-images.githubusercontent.com/3047049/92550672-81bd8c80-f275-11ea-98e4-06f84c94aebc.gif)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-09 at 08 22 03](https://user-images.githubusercontent.com/3047049/92550696-926e0280-f275-11ea-85fd-32ee6e852781.png)


Please feel free to comment if this is what you were looking for or if you need something else?

**Comment by nimisis** [comment]
This is a very helpful solution. Thanks!
